# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  create:
    tags:
      - v*
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Python wheels manylinux build
        uses: RalfG/python-wheels-manylinux-build@v0.3.4
        with:
          build-requirements: 'numpy cython'
          
      - name: Publish wheels to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |          
          python -m pip install --upgrade pip
          pip install twine
          python -m twine upload dist/*-manylinux*.whl

